spring:
  application:
    name: mini

  # Database ?? ??
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    username: postgres
    password: hw1234
    driver-class-name: org.postgresql.Driver

  # JPA ? Hibernate ??
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect